language: php

php:
  - 5.4
  - 5.5

env:
  global:
    - MODULE_NAME='entity_embed'
    - MODULE_TEST_GROUP='entity_embed'
    - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
    - DRUPAL_VERSION='8.0.x'

matrix:
  allow-failures:
    - php: 5.5

install:
  # Move the checked out module into the correct structure.
  - mkdir /tmp/$MODULE_NAME
  - mv * /tmp/$MODULE_NAME/
  - git clone --branch $DRUPAL_VERSION $DRUPAL_REPO drupal --depth 1
  - mv /tmp/$MODULE_NAME drupal/modules/
  - cd drupal/modules/$MODULE_NAME

  # Install dependencies.
  - composer install

before_script:
  # This fixes a fail when install Drupal.
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install Drupal and enable the required modules (including this one).
  - mysql -e 'create database drupal;'
  - ./vendor/bin/drush --yes site-install testing --db-url="mysql://root@127.0.0.1/drupal"
  - ./vendor/bin/drush --yes en $MODULE_NAME simpletest

  # Start a web server.
  - nohup ./vendor/bin/drush runserver 127.0.0.1:8080 &

script:
  # Run code sniffer.
  - ./vendor/bin/phpcs --report=full --standard=./vendor/drupal/coder/coder_sniffer/Drupal --ignore="./vendor/*" --extensions=module,php .

  # Run the tests
  - ./vendor/bin/drush test-run --uri http://127.0.0.1:8080 entity_embed
